const Map<String, Map<String, dynamic>> kPlans = {
  '1m': {
    'id': '1m',
    'months': 1,
    'labelKey': 'month_1',
    'prices': {'USD': 1.3},
    'perMonthPrices': {'USD': 1.3},
    'discount': null,
    'popular': false,
  },
  '3m': {
    'id': '3m',
    'months': 3,
    'labelKey': 'month_3',
    'prices': {'USD': 3.5},
    'perMonthPrices': {'USD': 1.17},
    'discount': '10%',
    'discountKey': 'off_10',
    'popular': false,
  },
  '6m': {
    'id': '6m',
    'months': 6,
    'labelKey': 'month_6',
    'prices': {'USD': 7.0},
    'perMonthPrices': {'USD': 1.17},
    'discount': '23%',
    'discountKey': 'off_23',
    'popular': true,
  },
  '1y': {
    'id': '1y',
    'months': 12,
    'labelKey': 'year_1',
    'prices': {'USD': 12.0},
    'perMonthPrices': {'USD': 1.0},
    'discount': '36%',
    'discountKey': 'off_36',
    'popular': false,
  },
};

const Map<String, Map<String, String>> kCurrencies = {
  'USD': {'symbol': '\$', 'name': 'Dollar (\$)'},
};

const List<Map<String, String>> kCountries = [
  {'name': 'United States', 'flag': '🇺🇸', 'code': 'US'},
  {'name': 'United Kingdom', 'flag': '🇬🇧', 'code': 'GB'},
  {'name': 'Germany', 'flag': '🇩🇪', 'code': 'DE'},
  {'name': 'France', 'flag': '🇫🇷', 'code': 'FR'},
  {'name': 'Japan', 'flag': '🇯🇵', 'code': 'JP'},
  {'name': 'South Korea', 'flag': '🇰🇷', 'code': 'KR'},
  {'name': 'Singapore', 'flag': '🇸🇬', 'code': 'SG'},
  {'name': 'Canada', 'flag': '🇨🇦', 'code': 'CA'},
  {'name': 'Australia', 'flag': '🇦🇺', 'code': 'AU'},
  {'name': 'Netherlands', 'flag': '🇳🇱', 'code': 'NL'},
  {'name': 'Switzerland', 'flag': '🇨🇭', 'code': 'CH'},
  {'name': 'Brazil', 'flag': '🇧🇷', 'code': 'BR'},
  {'name': 'India', 'flag': '🇮🇳', 'code': 'IN'},
  {'name': 'Turkey', 'flag': '🇹🇷', 'code': 'TR'},
  {'name': 'Russia', 'flag': '🇷🇺', 'code': 'RU'},
  {'name': 'Kyrgyzstan', 'flag': '🇰🇬', 'code': 'KG'},
  {'name': 'Kazakhstan', 'flag': '🇰🇿', 'code': 'KZ'},
  {'name': 'Uzbekistan', 'flag': '🇺🇿', 'code': 'UZ'},
  {'name': 'Italy', 'flag': '🇮🇹', 'code': 'IT'},
  {'name': 'Spain', 'flag': '🇪🇸', 'code': 'ES'},
  {'name': 'Poland', 'flag': '🇵🇱', 'code': 'PL'},
  {'name': 'Sweden', 'flag': '🇸🇪', 'code': 'SE'},
  {'name': 'Norway', 'flag': '🇳🇴', 'code': 'NO'},
  {'name': 'Finland', 'flag': '🇫🇮', 'code': 'FI'},
];
